In [3]:
import scipy.spatial
import numpy as np



In [25]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        super(Symetric,self).__setitem__(index,value)
        super(Symetric,self).__setitem__(index,value)
        
def symetric(Z):
    return np.asarray(Z+Z.T - np.diag(Z.diagonal())).view(Symetric)

S=symetric(np.random.randint(0,10,(5,5)))
S[2,3]=42
print(S)

[[ 3  8  5  9 14]
 [ 8  1  7 17  2]
 [ 5  7  9 42 10]
 [ 9 17  6  8 12]
 [14  2 10 12  4]]


In [26]:
p,n=10,20
M=np.ones((p,n,n))
V=np.ones((p,n,1))
S=np.tensordot(M,V,axes=[[0,2],[0,1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


In [28]:
Z=np.ones((16,16))
k=4
S=np.add.reduceat(np.add.reduceat(Z,np.arange(0,Z.shape[0],k),axis=0),
                 np.arange(0,Z.shape[1],k),axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]
